merge feat/confloader to dev/0.0.1
Memoscopy/libMMU pull request #9
Opened 2024-05-24 08:51 UTC by Esgr0bar

2024-05-27 11:05 UTC, Esgr0bar commented
improvement by using 'anyhow' instead of 'Box<dyn Error>' : 
```rust
fn load_config(file_path: &str) -> Result<MachineConfig> {
    let config_str = fs::read_to_string(file_path)
        .with_context(|| format!("Failed to read configuration file: {}", file_path))?;
    let config: MachineConfig = match file_path.rsplit('.').next().ok_or_else(|| anyhow::anyhow!("No file extension found"))? {
        "toml" => toml::from_str(&config_str)
            .with_context(|| format!("Failed to parse TOML configuration file: {}", file_path))?,
        _ => return Err(anyhow::anyhow!("Unsupported file format: {}", file_path)),
    };
    Ok(config)
} 
```

2024-05-28 08:26 UTC, shard77 commented
> improvement by using 'anyhow' instead of 'Box dyn Error' :
> 
> ```rust
> fn load_config(file_path: &str) -> Result<MachineConfig> {
>     let config_str = fs::read_to_string(file_path)
>         .with_context(|| format!("Failed to read configuration file: {}", file_path))?;
>     let config: MachineConfig = match file_path.rsplit('.').next().ok_or_else(|| anyhow::anyhow!("No file extension found"))? {
>         "toml" => toml::from_str(&config_str)
>             .with_context(|| format!("Failed to parse TOML configuration file: {}", file_path))?,
>         _ => return Err(anyhow::anyhow!("Unsupported file format: {}", file_path)),
>     };
>     Ok(config)
> } 
> ```
 I thought about this, but I think we can keep the `Box<dyn Error>` for now, the difference with anyhow is little (particularly in our use case, since we don't need anyhow's extra features), just so that we don't add too much external crates.

2024-05-28 09:46 UTC, standard3 commented on Cargo.toml
>  authors = ["Théo Abel <theo.abel53@gmail.com>"] # todo: add other contributors
Add yourself here

2024-05-28 09:47 UTC, standard3 commented on src/configuration.rs
> +#[derive(Debug, Serialize, Deserialize)]
Would be cool to implement other common traits, e.g: https://stevedonovan.github.io/rustifications/2018/09/08/common-rust-traits.html

2024-05-28 09:48 UTC, standard3 commented on src/configuration.rs
> +struct MachineConfig {
Same here

2024-05-28 09:48 UTC, standard3 commented on src/configuration.rs
> +#[derive(Serialize, Deserialize, Debug)]
Same here

2024-05-28 09:59 UTC, standard3 requested changes

2024-05-28 09:59 UTC, standard3 commented on src/configuration.rs
> +fn load_config(file_path: &str) -> Result<MachineConfig, anyhow::Error> {
Replace `file_path` type with [std::path:Path](https://doc.rust-lang.org/std/path/struct.Path.html), as this is a better practise.

You don't need to specify `anyhow::Error` for the return type, `Result<MachineConfig>` is sufficient.

2024-05-28 09:59 UTC, standard3 commented on src/configuration.rs
> +    let config: MachineConfig = match file_path.rsplit('.').next().context("No file extension found")? {
I don't specifically have a pre-made solution but handling the parsing of a file based on its extension isn't a very good practise. The extension is not a proof a file is of a certain type.

2024-05-28 09:59 UTC, standard3 commented on tests/test.json
I see 4 configuration test files but no tests testing the function that parses those ?
Also, would be cool if those were in a dedicated directory for configuration tests.

2024-05-28 09:59 UTC, standard3 commented on src/configuration.rs
> +struct MemorySpace {
Those structs/enums should be in a dedicated module as they will be used from other things than configuration.

2024-05-28 09:59 UTC, standard3 commented on src/configuration.rs
> +        "toml" => toml::from_str(&config_str)
No validation whatsoever for the loaded content ? What if a specified MMU mode doesn't exists ?

2024-06-18 14:59 UTC, standard3 commented on src/configuration.rs
> +impl TryFromPath for Machine {
wip

2024-06-18 15:00 UTC, standard3 commented on src/configuration.rs
> +        let machine: Machine = toml::from_str(&configuration)?;
wip

2024-06-19 10:31 UTC, shard77 approved these changes
LGTM - nothing to add here as of right now

2024-06-19 10:31 UTC, shard77 commented on src/configuration.rs
> +        "json" => serde_json::from_str(&config_str)?,
I don't think there's a need to add different formats here, just keep `toml`

2024-06-19 10:31 UTC, shard77 commented on src/configuration.rs
> +#[derive(Debug, Serialize, Deserialize)]
@standard3 which trait for example? I don't really see any useful use case for other traits implems than those that are already present.

2024-06-19 10:31 UTC, shard77 commented on src/configuration.rs
> +struct MemorySpace {
agreed on that one, planned to move it in the future but we can also do it on this PR

2024-06-19 10:31 UTC, shard77 commented on src/configuration.rs
> +fn load_config(file_path: &str) -> Result<MachineConfig, anyhow::Error> {
> Replace `file_path` type with [std::path:Path](https://doc.rust-lang.org/std/path/struct.Path.html), as this is a better practise.
> 
> You don't need to specify `anyhow::Error` for the return type, `Result<MachineConfig>` is sufficient.

@standard3 I disagree, I belive it's better if we let that to disambiguate.

2024-06-19 10:31 UTC, shard77 commented on src/configuration.rs
> +    let config: MachineConfig = match file_path.rsplit('.').next().context("No file extension found")? {
IMO this is fine, no need to go overkill here, the extension is sufficient, error handling is done so I don't see why we should check, would also probably result in lots of overhead if we add it - or at least an additional crate

2024-06-19 11:07 UTC, standard3 approved these changes

2024-06-19 15:21 UTC, merged